/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AskIndexRouteImport } from './routes/ask/index'
import { Route as IdeasIndexRouteImport } from './routes/ideas/index'
import { Route as IdeasIdeaIdRouteImport } from './routes/ideas/$ideaId'
import { Route as InboxIndexRouteImport } from './routes/inbox/index'
import { Route as NotesIndexRouteImport } from './routes/notes/index'
import { Route as NotesNoteIdRouteImport } from './routes/notes/$noteId'
import { Route as PlanIndexRouteImport } from './routes/plan/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as TasksTaskIdRouteImport } from './routes/tasks/$taskId'
import { Route as TimeIndexRouteImport } from './routes/time/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AskIndexRoute = AskIndexRouteImport.update({
  id: '/ask/',
  path: '/ask/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasIndexRoute = IdeasIndexRouteImport.update({
  id: '/ideas/',
  path: '/ideas/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasIdeaIdRoute = IdeasIdeaIdRouteImport.update({
  id: '/ideas/$ideaId',
  path: '/ideas/$ideaId',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxIndexRoute = InboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesNoteIdRoute = NotesNoteIdRouteImport.update({
  id: '/notes/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanIndexRoute = PlanIndexRouteImport.update({
  id: '/plan/',
  path: '/plan/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeIndexRoute = TimeIndexRouteImport.update({
  id: '/time/',
  path: '/time/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ideas/$ideaId': typeof IdeasIdeaIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/ask/': typeof AskIndexRoute
  '/ideas/': typeof IdeasIndexRoute
  '/inbox/': typeof InboxIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/plan/': typeof PlanIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/time/': typeof TimeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ideas/$ideaId': typeof IdeasIdeaIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/ask': typeof AskIndexRoute
  '/ideas': typeof IdeasIndexRoute
  '/inbox': typeof InboxIndexRoute
  '/notes': typeof NotesIndexRoute
  '/plan': typeof PlanIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/time': typeof TimeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ideas/$ideaId': typeof IdeasIdeaIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/ask/': typeof AskIndexRoute
  '/ideas/': typeof IdeasIndexRoute
  '/inbox/': typeof InboxIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/plan/': typeof PlanIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/time/': typeof TimeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ideas/$ideaId'
    | '/notes/$noteId'
    | '/projects/$projectId'
    | '/tasks/$taskId'
    | '/ask/'
    | '/ideas/'
    | '/inbox/'
    | '/notes/'
    | '/plan/'
    | '/projects/'
    | '/settings/'
    | '/tasks/'
    | '/time/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ideas/$ideaId'
    | '/notes/$noteId'
    | '/projects/$projectId'
    | '/tasks/$taskId'
    | '/ask'
    | '/ideas'
    | '/inbox'
    | '/notes'
    | '/plan'
    | '/projects'
    | '/settings'
    | '/tasks'
    | '/time'
  id:
    | '__root__'
    | '/'
    | '/ideas/$ideaId'
    | '/notes/$noteId'
    | '/projects/$projectId'
    | '/tasks/$taskId'
    | '/ask/'
    | '/ideas/'
    | '/inbox/'
    | '/notes/'
    | '/plan/'
    | '/projects/'
    | '/settings/'
    | '/tasks/'
    | '/time/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdeasIdeaIdRoute: typeof IdeasIdeaIdRoute
  NotesNoteIdRoute: typeof NotesNoteIdRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  AskIndexRoute: typeof AskIndexRoute
  IdeasIndexRoute: typeof IdeasIndexRoute
  InboxIndexRoute: typeof InboxIndexRoute
  NotesIndexRoute: typeof NotesIndexRoute
  PlanIndexRoute: typeof PlanIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  TimeIndexRoute: typeof TimeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask/': {
      id: '/ask/'
      path: '/ask'
      fullPath: '/ask/'
      preLoaderRoute: typeof AskIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/': {
      id: '/ideas/'
      path: '/ideas'
      fullPath: '/ideas/'
      preLoaderRoute: typeof IdeasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/$ideaId': {
      id: '/ideas/$ideaId'
      path: '/ideas/$ideaId'
      fullPath: '/ideas/$ideaId'
      preLoaderRoute: typeof IdeasIdeaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/': {
      id: '/inbox/'
      path: '/inbox'
      fullPath: '/inbox/'
      preLoaderRoute: typeof InboxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$noteId': {
      id: '/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof NotesNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/': {
      id: '/plan/'
      path: '/plan'
      fullPath: '/plan/'
      preLoaderRoute: typeof PlanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time/': {
      id: '/time/'
      path: '/time'
      fullPath: '/time/'
      preLoaderRoute: typeof TimeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdeasIdeaIdRoute: IdeasIdeaIdRoute,
  NotesNoteIdRoute: NotesNoteIdRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  TasksTaskIdRoute: TasksTaskIdRoute,
  AskIndexRoute: AskIndexRoute,
  IdeasIndexRoute: IdeasIndexRoute,
  InboxIndexRoute: InboxIndexRoute,
  NotesIndexRoute: NotesIndexRoute,
  PlanIndexRoute: PlanIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  TimeIndexRoute: TimeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
